[package]
name = "copy_from_str"
version = "1.0.0"
authors = ["Konrad Borowski <copyfromstr@borowski.pw>"]
repository = "https://github.com/xfix/copy_from_str"
license = "MIT/Apache-2.0"
description = "An extension trait to copy a string into another string"
keywords = ["no_std", "str", "string"]
categories = ["no-std", "rust-patterns"]
documentation = "https://docs.rs/copy_from_str"
readme = "README.md"

[badges]
travis-ci = { repository = "xfix/copy_from_str" }

[dependencies]
extension-trait = "0.1.2"

[dev-dependencies]
quickcheck = "0.6.2"
